version: '3'

services:
  db:
    image: postgres:12
    env_file: ./db/.env_db

  code:
    build: .

    ports:
      - "8080:8080"
    depends_on:
      - db
    command: bash ./subscription/start.sh
    env_file: ./.env