# Generated by Django 3.1.1 on 2020-09-09 22:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.editor')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(default=datetime.datetime(2021, 9, 9, 22, 40, 43, 111336))),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.customer')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.journal')),
            ],
        ),
    ]
