# Generated by Django 3.1.1 on 2020-09-10 10:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200910_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to='api.customer'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 9, 10, 10, 50, 47, 808677)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to='api.journal'),
        ),
    ]
